### PR TITLE
include explicitely slack on our coc

### PR DESCRIPTION
**Pull request by sonaht**

### CODE REVIEW

**Comment by gsaslis** [comment]
I think it is worth adding sth like "any kind of event" too @sonaht

**Comment by sonaht** [comment]
I believe that "should apply to all means of communication" supersets the any kind of event...sounds similar I mean

**Comment by sonaht** [comment]
Open to direct changes tho. Let me know

**Comment by gsaslis** [comment]
To provide some background / context, this topic was discussed in the last devstaff org meetup, where we decided we need to make the scope of the CoC more explicit, so that it is clear to everyone where it is applicable or not. 

As such, it is only the wording itself we are discussing in this PR, not the intent to add this in or not (that intent was agreed upon in the org meetup itself, where such decisions are taken anyway. 

I will merge and close, but please feel free to raise a new GitHub issue if there are any objections, etc.

**Comment by sonaht** [comment]
superb !!!

**Pull request merged**
