### PR TITLE
added meetup 11 - NoSQL

### PR DESCRIPTION
**Pull request by sonaht**

### CODE REVIEW

**Comment by gsaslis** [comment]
why was the date format changed here?

**Comment by sonaht** [comment]
I believe all dates should be in a format that we all are used in seeing in this country.

I presumed no harm in that!!

**Comment by DaKnOb** [comment]
We were simply following an [International Standard](http://www.iso.org/iso/home/standards/iso8601.htm).

**Comment by sonaht** [comment]
Sure not a problem, as I believe it is not a problem to use the date in a GR friendly format. It actually is easier, developer or not. Lets not make this a big issue.

**Comment by gsaslis** [comment]
Ok, fair enough. 

I thought I'd check, cause `yyyy-MM-dd` is: 
* also international
* sortable
* non-ambiguous (and therefore even more international)

but as long as most of you prefer that, it's ok I guess...

**Pull request merged**
