### PR TITLE
Bitcoin Getting Started guide

### PR DESCRIPTION
**Pull request by gsaslis**
Added some initial info to serve as the basis of a work-in-progress guide to Bitcoin.

### CODE REVIEW

**Comment by sonaht** [comment]
Why here and not on the meetup repo for the bitcoins ?

**Comment by zakkak** [comment]
I guess it's better here since it's a document and not the presentation of the meetup.  If we place it on the meetup repo and not here then someone might visit documents to see what is available and miss it.  My experience is that on the meetup repos we only put the slides, so somebody might not look there.

**Comment by gsaslis** [comment]
hmmm good point. I just felt it would be more noticeable here... 

What do you think?

**Comment by sonaht** [comment]
This is a never ending story then, since documents of interest might arise from all and every meetup, thus making this a central repo, which is not the case imho. I believe meetup related documentation should exist in the meetup repository and surely a proper link can exist in the central repo as well

**Comment by gsaslis** [comment]
Hmm I see your point @sonaht ...

Tbh I only see this doc as coincidentally related to the meetup.

Bitcoin is so huge / important that I see this as a general purpose doc - to be used as a way to educate ppl...

**Comment by sonaht** [comment]
As long as you tell me where the limits are ? Or just publish the doc on slack in the appropriate channel. Also assume that everyone will wish to publish some doc on the main repo relating to something huge/important ... it will eventually turn the main repo into a document repo or something similar.

**Comment by zakkak** [comment]
In that case the documents folder should not be on the main repo and should live on its own repo.

**Comment by sonaht** [comment]
I think so too @zakkak, a separate documentation repo will be better (if it is actually needed). I still think that this is meetup material and should go in there.

**Comment by gsaslis** [comment]
@sonaht tbh, i don't think we need to clearly define any limits or hard policy. there are so few documents still that I don't see a need for such work to be done now. 

The main repo already has a documents folder and we can simply use it for anything that falls in the document category really... 

If - despite our expectations - lots of documents start popping up, I propose we deal with that there and then.

**Comment by sonaht** [comment]
I am dropping this under protest.

Final thoughts: Imagine what will happen when I pull request a few thousands of amazingly delicious recipes... (food seems to be a buzz word in Slack lately). My point has been missed all together.

**Pull request merged**
