### PR TITLE
Secure Analytics

### PR DESCRIPTION
**Pull request by DaKnOb**

### CODE REVIEW

**Comment by gsaslis** [comment]
@daknob don’t you think we should update this to current process? 

Given that we now have votes on meetup.con does it make sense to keep this text (and even analytics app) lying around?

**Comment by mzampetakis** [comment]
I propose writing down the new process and leave this just for historical reasons! We might sometime later use it again!

**Comment by mzampetakis** [comment]
So, do you propose writing down the new process, but keep a note for the old one too?

**Comment by gsaslis** [comment]
Well... this would have the side effect that it would update the “last updated” time for that text to “today”, causing folks to believe it is current (when it is not... We do not use this today...)

**Comment by DaKnOb** [comment]
It is more secure that way though.. The other way isn’t..

**Comment by gvre** [comment]
True, but not a big issue in this case. Anyway, @gsaslis how about adding a message at the top of the page about the new analytics, etc? That would also help in cases where users visit `analytics.devstaff.gr` directly, without clicking any link. I think it's a good solution that makes all of us happy :) 
@sonaht @mzampetakis What do you guys think about that?

**Comment by gsaslis** [comment]
I opened #302 so we can finally have this resolved as well.

**Comment by gsaslis** [comment]
Btw, I am closing this - but please feel free to reopen if you think any concerns mentioned here are not covered in #302.

**Pull request closed without merging**
