### PR TITLE
Updates StartHere.md to reflect new voting style

### PR DESCRIPTION
**Pull request by zakkak**
Moved from `:+1:` comments to [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments).

### CODE REVIEW

**Comment by DaKnOb** [comment]
Does this require everyone to vote again on the same topics they did before?

**Comment by zakkak** [comment]
I guess not.  We can gradually transit by making the analytics app count both (and ignore double votes of the same user).

**Comment by DaKnOb** [comment]
@zakkak That means we need a PR there too, and that's more complicated (?) especially if they don't expose that to the API yet..

**Comment by DaKnOb** [comment]
But I think that's the way to go.

**Comment by DaKnOb** [comment]
@/all I suggest waiting until the Analytics PR is through. It may take long because we need an author, but we can't merge this just yet.

**Comment by zakkak** [comment]
AFAIK [the API supports what we want to do](https://developer.github.com/v3/reactions/#list-reactions-for-an-issue) it but it's not stable yet meaning that we might need to revise it in the future (hopefully, not many changes will be needed).

@sonaht I love how you just ignored @DaKnOb :)

**Comment by zakkak** [comment]
@DaKnOb is right, to avoid confusion about vote counting we need to patch the analytics as well.  Any volunteers?

**Comment by DaKnOb** [comment]
@zakkak Can you send a PR to revert this commit? How do you revert a PR? :P

**Comment by gsaslis** [comment]
@DaKnOb ask @sonaht who went ahead and merged it........ :D

**Comment by DaKnOb** [comment]
@gsaslis He's mad at me.. :P

**Comment by zakkak** [comment]
@DaKnOb instead of looking around on how to revert it (which I don't think one can to from the we UI) it would be better if someone could patch the analytics app (it shouldn't be that hard :P).

Also note that we have a time window until the next time we have to choose a topic (till then it's kind of OK if the analytics app is not working properly)

**Comment by sonaht** [comment]
Hello, guys

I can always revert the PR and be done with it.

Point is that the community can help and patch the analytics app as fast as well.

@DaKnOb not mad at U at all... still w8ing for the main site PR changes as well.

@zakkak love u2

either way just let me know if u need me to revert or not, i believe we should not revert.

Voting will not be as accurate as it is (!) but I hope that bright young developers of the community will patch this during the week.

**Comment by msti** [comment]
Is there any reason to rush? The api is not stable yet, there are no volunteers and it is not like this is a huge improvement. Unless @sonaht and @zakkak are confident that we will be able to do this without much confusion I would say to revert it. 

Also, the PR writes about downvoting. Has this been discussed? As far as I remember we do not count the down votes.

**Comment by padeler** [comment]
I agree with @msti, lets not rush. We have a process that works, we should replace it with another that works better, not break it first and fix it later.

**Comment by sonaht** [comment]
The change has been reverted.

Sometimes it is required that change is forced but not this time.

Lets discuss this over beers and see what comes out !!!

**Comment by zakkak** [comment]
We actually rushed both ways!

@msti In the first meetups we said that negative votes `:-1:` would also be considered, but in the process it was ditched (I think without much discussion, it was just harder to do so we went the other way).

**Comment by msti** [comment]
I am not fond of downvoting. Upvoting seems fair enough to me. Let's discuss this over the next beer up as well.

**Pull request merged**
