### PR TITLE
Adds beerup info, agenda and moments

### PR DESCRIPTION
**Pull request by kabitakis**

### CODE REVIEW

**Comment by gsaslis** [comment]
@kabitakis / @sonaht : wouldn't the wiki be more suitable? 
(we could even edit the wiki from our mobile during the beerups  ; )   )

**Comment by kabitakis** [comment]
Why didn't you say so at the beerup? I just implemented what has been decided.
Furthermore, 'to anelaves!' and if we like it we may even use it :P

**Comment by sonaht** [comment]
ok again :+1:

**Comment by gsaslis** [comment]
@kabitakis, i wasn't there when this was discussed  : )

it's ok, no worries -- I might open another PR about this soon


-- 
Yorgos Saslis
Software Engineer

**Comment by kabitakis** [comment]
This is what happens when you don't stay for a second beer! You also missed some other interesting discussions :)

**Pull request merged**
