### PR TITLE
Add new sponsorship packages

### PR DESCRIPTION
**Pull request by gsaslis**
We've agreed in the org meetups to open up a few sponsorship packages that will primarily allow us to distribute some swag to our community members, so we can promote the DevStaff brand name. 

This is an attempt at describing what those packages could look like. 

Feedback is more than welcome!

### CODE REVIEW

**Comment by ealefrag** [comment]
I would suggest giving slightly more exposure to the Sponsors in order to persuit them (and thank them for the contribution). More specifically, I was thinking something like mentioning them prior to the event at meetup.com or/and allowing them to bring a banner (predifined size) on-premises for as long as their sponsorship is in effect.

**Comment by gsaslis** [comment]
@ealefrag thanks! 

I should really have made it clearer I guess, that it is the sponsors who are knocking on our door, not the other way round. Considering that is the case, I think we can afford to minimize the "noise" this kind of thing could bring to our meetups. 

Does that make sense?

**Comment by ealefrag** [comment]
Makes perfect sense now!

**Comment by DaKnOb** [comment]
I agree and support the merge of this Pull Request.

**Comment by gsaslis** [comment]
@kabitakis / @sonaht / @estavrak / @sbehnsen / @sstauross if you're ok with this please approve the merge of the PR, so we have a majority and we can take this forward.

**Comment by sonaht** [comment]
Guys unless someone has a different view I will be merging tomorrow

**Comment by kabitakis** [comment]
The updates made by @gsaslis are valid and have been discussed and approved in org meetings.

My only concern is to communicate these updates as much as possible in order we give equal (not possible but you get the idea) opportunities to every company interested in sponsorships. A message in slack's general channel, facebook and linkedin posts would do. Also an email to our current sponsors and the ones which have expressed their interest would be nice.

At some point I would also like to talk about ad hoc sponsorships as well as past contributions to the community, by people and organisations which did not ask for anything in return, but that's a topic for another github issue / PR / org meeting.

**Pull request merged**
