### PR TITLE
Add meetup 84

### PR DESCRIPTION
**Pull request by Bellangelo**

### CODE REVIEW

**Comment by mzampetakis** [comment]
It seems that the folder at `meetups/meetup84-ChatGPT-and-Large-Language-Models` is missing. You can add there a Readme.md with the meetup's title in order for git not to ignore the folder.

**Comment by Bellangelo** [comment]
> It seems that the folder at `meetups/meetup84-ChatGPT-and-Large-Language-Models` is missing. You can add there a Readme.md with the meetup's title in order for git not to ignore the folder.

@mzampetakis The folder is there and it already contains a README. Maybe you checked it through a non-updated branch?
I have checked if I made any typos but my IDE correctly finds the folder when I click on the url. Am I missing something?

**Comment by mzampetakis** [comment]
You are right. My bad. This has already been merged!

**Review by mzampetakis — APPROVED** [review]
Looks good!

**Pull request merged**
